### ISSUE TITLE
Using a empty template file raises an exception

### ISSUE THREAD

**Issue by LeSuisse** [Frky/confiture#5]
When we try to validate a configuration file with an empty template a ConfigFileError is raised. This exception should not raised, an empty YAML file is valid according to the specification.
To be consistent with the specification, confiture should accept an empty template file and in that case just validate any configuration file with a valid syntax.

**Comment by Frky** [comment]
You are damn right. I should definitively fix this.

**Comment by Frky** [comment]
(Fixed)
